"""
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

"""
解题思路：
分别对两个字符串转为列表
并对列表得值进行ascii转码
然后对两组列表相继和0做异或操作
"""


class Solution(object):

    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        result = 0
        lst_s = [ord(i) for i in list(s)]
        lst_t = [ord(j) for j in list(t)]
        for i in lst_s:
            result ^= i
        for i in lst_t:
            result ^= i
        return chr(result)
